In [1]:
import numpy as np

In [2]:
#READ THE DATASET
from sklearn.datasets import load_iris

/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [3]:
iris = load_iris()

/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/datasets/base.py:242: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/datasets/base.py:246: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the

In [4]:
type(iris) #BUNCH TYPE OF OBJECT

sklearn.utils.Bunch

In [11]:
print(iris.DESCR) #FEATURES - SEPAL LENGTH, SEPAL WIDTH, PETAL LENGTH, PETALWIDTH

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
#GRAB THE FEATURE AND LABEL INFORMATION
X = iris.data

In [6]:
X #SEPAL LENGTH, SEPAL WIDTH, PETAL LENGTH, PETAL WIDTH IN NUMPY ARRAY

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
#GRAB LABELS: CLASSIFICATIONS
Y = iris.target
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
#CONVERT INTO ONE-HOT ENCODING SYSTEM FOR KERAS

#VECTOR THAT IS 0 WHEN DOESN'T MATCH UP

#class 0 - - > [1, 0, 0]
#class 1 - - > [0, 1, 0]
#class 2 - - > [0, 0, 1]

In [9]:
from keras.utils import to_categorical

2023-06-07 16:49:43.832219: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [10]:
Y = to_categorical(Y)

In [11]:
Y.shape

(150, 3)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_TRAIN, X_TEST, Y_TRAIN, Y_TEST = train_test_split(X, Y, test_size = 0.33, random_state = 42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
#SCALE ALL TO VALUES 0-1
scaler_object = MinMaxScaler()

In [16]:
#FIT TO TRAINING DATA
scaler_object.fit(X_TRAIN)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaled_X_TRAIN = scaler_object.transform(X_TRAIN)

In [18]:
scaled_X_TEST = scaler_object.transform(X_TEST)

In [19]:
#SCALED VERSIONS OF THE DATA

from keras.models import Sequential
from keras.layers import Dense

In [20]:
model = Sequential()
#ADD A LAYER

#NO OF NEURONS, NO OF FEATURES, ACTIVATION FUNCTION
model.add(Dense(8, input_dim = 4, activation='relu'))
model.add(Dense(8, input_dim = 4, activation='relu'))
model.add(Dense(3, activation='softmax'))

#COMPILE THE MODEL
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

2023-06-07 17:06:20.318798: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [21]:
#ASK FOR SUMMARY OF MODEL
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [22]:
#FIT THE MODEL ON SCALED DATA

#VERBOSE DEFINES HOW DETAILED PROGRESS IS TO BE SHOWN
model.fit(scaled_X_TRAIN, Y_TRAIN, epochs=150, verbose=1)

Epoch 1/150
4/4 [==============================] - 1s 3ms/step - loss: 1.1085 - accuracy: 0.3100
Epoch 2/150
4/4 [==============================] - 0s 4ms/step - loss: 1.1035 - accuracy: 0.3100
Epoch 3/150
4/4 [==============================] - 0s 4ms/step - loss: 1.0989 - accuracy: 0.3200
Epoch 4/150
4/4 [==============================] - 0s 3ms/step - loss: 1.0951 - accuracy: 0.3200
Epoch 5/150
4/4 [==============================] - 0s 4ms/step - loss: 1.0918 - accuracy: 0.3800
Epoch 6/150
4/4 [==============================] - 0s 3ms/step - loss: 1.0880 - accuracy: 0.4500
Epoch 7/150
4/4 [==============================] - 0s 4ms/step - loss: 1.0843 - accuracy: 0.5300
Epoch 8/150
4/4 [==============================] - 0s 3ms/step - loss: 1.0806 - accuracy: 0.5600
Epoch 9/150
4/4 [==============================] - 0s 3ms/step - loss: 1.0766 - accuracy: 0.5600
Epoch 10/150
4/4 [==============================] - 0s 5ms/step - loss: 1.0726 - accuracy: 0.6000
Epoch 11/150
4/4 [===========

4/4 [==============================] - 0s 3ms/step - loss: 0.5957 - accuracy: 0.6800
Epoch 85/150
4/4 [==============================] - 0s 3ms/step - loss: 0.5911 - accuracy: 0.6800
Epoch 86/150
4/4 [==============================] - 0s 4ms/step - loss: 0.5866 - accuracy: 0.6800
Epoch 87/150
4/4 [==============================] - 0s 3ms/step - loss: 0.5822 - accuracy: 0.6800
Epoch 88/150
4/4 [==============================] - 0s 3ms/step - loss: 0.5780 - accuracy: 0.6800
Epoch 89/150
4/4 [==============================] - 0s 4ms/step - loss: 0.5736 - accuracy: 0.6800
Epoch 90/150
4/4 [==============================] - 0s 4ms/step - loss: 0.5691 - accuracy: 0.6800
Epoch 91/150
4/4 [==============================] - 0s 3ms/step - loss: 0.5643 - accuracy: 0.6800
Epoch 92/150
4/4 [==============================] - 0s 4ms/step - loss: 0.5597 - accuracy: 0.6900
Epoch 93/150
4/4 [==============================] - 0s 4ms/step - loss: 0.5549 - accuracy: 0.7000
Epoch 94/150
4/4 [===============

In [23]:
#95% FINAL ACCURACY

In [27]:
#PART - 2


#SCALE THE TEST DATA: ALREADY DONE

np.argmax(model.predict(scaled_X_TEST), axis=-1)

2/2 [==============================] - 0s 4ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [28]:
#COMPARE PREDICTIONS WITH THE ONE-HOT ENCODED Y_TEST
predictions = np.argmax(model.predict(scaled_X_TEST), axis=-1)

2/2 [==============================] - 0s 3ms/step


In [32]:
#TRANSFORM THE Y_TEST BACK TO CLASSES
Y_TEST = Y_TEST.argmax(axis=1)

In [31]:
#COMPARE THE PREDICTIONS WITH TRUE VALUES
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [33]:
confusion_matrix(Y_TEST, predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]])

In [34]:
print(classification_report(Y_TEST, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

   micro avg       0.96      0.96      0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [36]:
#RUNNING A SUPER LARGE MODEL; EG FOR TEXT GENERATION;
#WE WANT TO SAVE AND LOAD THE MODEL

#SAVE THE MODEL
model.save('myfirstmodel.h5') #AUTOMATICALLY OVERWRITES

In [37]:
from keras.models import load_model

In [38]:
new_model = load_model('myfirstmodel.h5')

In [39]:
new_model.predict(scaled_X_TEST)

2/2 [==============================] - 0s 3ms/step


array([[8.74231160e-02, 5.40649116e-01, 3.71927828e-01],
       [9.90971446e-01, 6.02982193e-03, 2.99868081e-03],
       [1.19113550e-02, 1.02651879e-01, 8.85436833e-01],
       [7.74160549e-02, 5.29200613e-01, 3.93383265e-01],
       [6.44765496e-02, 4.30588543e-01, 5.04934967e-01],
       [9.79776800e-01, 1.37591241e-02, 6.46413118e-03],
       [1.26593113e-01, 6.38365149e-01, 2.35041782e-01],
       [2.61070449e-02, 2.35890970e-01, 7.38002002e-01],
       [5.78616373e-02, 3.16376030e-01, 6.25762343e-01],
       [1.06507301e-01, 6.21182263e-01, 2.72310525e-01],
       [4.23199013e-02, 3.64121735e-01, 5.93558311e-01],
       [9.81424153e-01, 1.28296735e-02, 5.74619044e-03],
       [9.91468549e-01, 5.72266988e-03, 2.80881370e-03],
       [9.83189225e-01, 1.16011631e-02, 5.20955678e-03],
       [9.94930565e-01, 3.42014246e-03, 1.64935936e-03],
       [7.60815516e-02, 5.85459530e-01, 3.38458985e-01],
       [2.15788167e-02, 1.76528633e-01, 8.01892579e-01],
       [1.12806566e-01, 6.06846

In [ ]:
#EVALUATING AND PREDICTING DATA DONEX